export enum ErrorCode {
  INVALID_MESSAGE = "INVALID_MESSAGE",
  ROOM_NOT_FOUND = "ROOM_NOT_FOUND",
  PEER_NOT_FOUND = "PEER_NOT_FOUND",
  PEER_NOT_IN_ROOM = "PEER_NOT_IN_ROOM",
  TRANSPORT_NOT_FOUND = "TRANSPORT_NOT_FOUND",
  PRODUCER_NOT_FOUND = "PRODUCER_NOT_FOUND",
  CONSUMER_NOT_FOUND = "CONSUMER_NOT_FOUND",
  MEDIA_ERROR = "MEDIA_ERROR",
  INTERNAL_ERROR = "INTERNAL_ERROR",
}

export interface ErrorPayload {
  code: ErrorCode;
  message: string;
  requestId?: string;
}
